file_format: "1"
id: hillside46rolling
name: Hillside46rolling
type: shield
url: https://github.com/mmccoyd/hillside/
requires: [pro_micro]
features:
  - keys
  - encoder
  - underglow
siblings:
  - hillside46rolling_left
  - hillside46rolling_right